[build] 
  publish = "public"
  command = "hugo --gc -b $DEPLOY_PRIME_URL"
  HUGO_VERSION = "0.55.6" 

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  command = "hugo --gc"

[context.deploy-preview]
  command = "hugo --gc --buildDrafts --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]