[build]
  command = "hugo --gc --minify"
  publish = "public"
  [build.environment]
    HUGO_VERSION = "0.147.9"

[context.production]
  command = "hugo --gc --minify"
  [context.production.environment]
    HUGO_ENV = "production"
    HUGO_VERSION = "0.147.9"

[context.deploy-preview]
  command = "hugo --gc --minify --buildDrafts --buildFuture -b $DEPLOY_PRIME_URL"
  [context.deploy-preview.environment]
    HUGO_VERSION = "0.147.9"