[build] 
  publish = "public"
  command = "hugo --gc --minify"
  HUGO_VERSION = "0.54.0" 

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"