baseURL: 'https://example.com'
theme: hugo-coder
languagecode: en
defaultcontentlanguage: en
title: TL;DR
paginate: 20
canonifyurls: true
pygmentsstyle: bw
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
params:
  author: Tim Sparg
  info: Full Stack DevOps and Magician
  description: Tim Spargs' personal website
  keywords: 'blog,developer,personal'
  avatarurl: images/avatar.jpg
  favicon_32: /img/favicon-32x32.png
  favicon_16: /img/favicon-16x16.png
  footercontent: but did you grok more than null
  hidecredits: false
  hidecopyright: false
  rtl: false
  math: false
  custom_css:
    - css/molokai.css
    - css/custom.css
  social:
    - name: Github
      icon: fab fa-github fa-2x
      weight: 1
      url: 'https://github.com/timothysparg/'
    - name: Linkedin
      icon: fab fa-linkedin-in fa-2x
      weight: 2
      url: 'https://www.linkedin.com/in/timothysparg/'
menu:
  main:
    - name: Blog
      weight: 1
      url: /posts/
    - name: About
      weight: 2
      url: /about/
