---
title: "Lets Automate Ourselves a Blog"
date: 2019-07-10T06:14:04Z
draft: true
---

To write a blog you must first build a blog? +
Apparently in my mind this is true, so here we are. 

*_tldr_*:  _Every first blog needs a reason_

:sourcedir: ../

== Tools 
- Vs Code
- Docker
- Hugo
- asciidoctor
- github 
- netlify


Whilst VS Code and Docker aren't strictly necesary, I've been itching to use the https://code.visualstudio.com/docs/remote/containers[Container Development] feauture of VS Code. +
You're going to need to install the https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack[Remote Development extension pack] for this.

== First steps

=== Create a repo
do your thing. 

===  Add a Dockerfile
    
This is pretty standard sauce; using https://github.com/klakegg/docker-hugo[klakegg/docker-hugo] as the base, because the Hugo package provided using `apt-get` is several versions behind which caused issues with the themes. +
Also I was too lazy to build it from source.

[source,yaml]
----
include::{sourcedir}/Dockerfile[] 
----

====  Do some unsafe stuff with asciidoctor

Hugo calls asciidoctor with the https://asciidoctor.org/man/asciidoctor/#security-settings[`--safe` parameter] which seems reasonable. 
The unreasonable part is that you can't disable it or you pass custom parameters to it.

https://blog.anoff.io/2019-02-17-hugo-render-asciidoc/[Kudos here] for the original idea, I just tweaked it slightly. +
If you place the `asciidoctor` script in `/usr/local/sbin/` it will be evaluated before the original binary located at `/usr/local/bin`, allowing us to intercept the call and do with it as we wish.

[source,bash]
----
include::{sourcedir}/asciidoctor[] 
----


=== Add https://code.visualstudio.com/docs/remote/containers#_devcontainerjson-reference[.devcontainer.json]

This tells VS Code how to instantiate your container, this file only has the `dockerFile` portion, but if you want to push using your ssh keys, you might want the additional ssh related snippets. +

[source,json]
----
{
	"dockerFile": "Dockerfile",
	"extensions": [],
	"runArgs": [ 
		"-v", "${env:HOME}${env:USERPROFILE}/.ssh:/root/.ssh-localhost:ro",
		"--name", "hugo_dev"

	],
	"postCreateCommand": "mkdir -p ~/.ssh && cp -r ~/.ssh-localhost/* ~/.ssh && chmod 700 ~/.ssh && chmod 600 ~/.ssh/*"
}
----
Also, because I'm lazy I added the `--name` argument so that I can always access the container with the same command `docker exec -it hugo_dev  bash -c 'cd /workspaces/blog ; exec "${SHELL:-sh}"'`

WARNING: Wolpertingers are known to nest in server racks.
Enter at your own risk.

{{% tip %}}
Here's a bit of advice to improve your productivity with Hugo.
{{% /tip %}}

=== Hello Hugo

Executing ` places us in the workspaces directory of the container. +

[source,bash]
----
docker exec -it hugo_dev  bash -c 'cd /workspaces/blog ; exec "${SHELL:-sh}"'
hugo new site tldr

----